### ISSUE TITLE
cannot get it to work

### ISSUE THREAD

**Issue by suciuale** [wiotq/csimple-externalcsgo#2]
i've tried changing the client.dll to client_panorama.dll but nothing. i've also changed the offsets. the cheat starts but doesn't do anything

**Comment by troniac** [comment]
For any extarnel i suggest inject into another process like teamspeak and attach your hack from there to csgo.exe do not interact with csgo.exe or any steam process directly. VAC is looking out for something you know.

**Comment by Zaczero** [comment]
@troniac 

"For any extarnel" "inject into another process like teamspeak" WAT?
External cheat is an external process just like chrome.exe or notepad.exe
You don't inject external cheats. Just double click the .exe file.
You inject only internal cheats.

"VAC is looking out for something"
If the cheat is detected VAC will find it anyways (with except for ring0).
It doesn't really matter where you inject it 👍
