### ISSUE TITLE
Can you update/not working in game

### ISSUE THREAD

**Issue by SnakeyLuck** [wiotq/csimple-externalcsgo#5]
im trying to use this cheat i built it successfully and when im in csgo with menu up i check boxes for glow and fov changer they dont work in game (i removed other features) i don't know really anything about coding and don't know whats up with it, if it needs offsets updating idk. i tried offsets but they are same as what i found on mpgh. i dont suppose anyone could help me?

**Comment by wiotq** [comment]
Fov changer was bugged, i'm fixing it right now, also i've updated offsets
